apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fund-management
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.frontend.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fund-management-frontend
                port: {number: 8080}
  tls:
    - hosts: [{{ .Values.frontend.domain }}]
