{{- range $component := list "backend" "frontend" "backup" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fund-management-{{ $component }}
automountServiceAccountToken: false
{{- end }}
